version: '3.1'

services:
  web:
     build:
       context: .
       dockerfile: Dockerfile_web
     container_name: web-app
     ports:
       - 80:80
     restart: always
     stdin_open: true
     tty: true
     depends_on:
       - mysql
  
  mysql:
     image: mysql:5.6
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: rootpwd
     healthcheck:
       test: ["CMD", "mysqladmin" ,"ping", "-h", "mysql"]
       timeout: 60s
       retries: 3

  config:
     build:
       context: .
       dockerfile: Dockerfile_config
     container_name: config-app
     depends_on:
       - mysql
       - web
 
  poc:
     build:
       context: .
       dockerfile: Dockerfile_poc
     container_name: poc-app
     depends_on:
       - web
       - config

