FROM debian:jessie
USER root

ADD File/poc.sh /poc.sh
ADD File/poc.py /poc.py
ADD File/requirements_poc.txt /requirements_poc.txt
ADD File/wait-for-it.sh /wait-for-it.sh


RUN chmod +x /poc.sh 
CMD ["bash", "-c", "echo 1 && bash /poc.sh"]
