name: DVE Test
on: [push, pull_request]
jobs: 
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Build Images And Backup
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: lishuang-star/web
        path: ./web
        tags: 1.0

    - name: Deploy DVE
      run: docker-compose up -d

    - uses: actions/setup-node@v2-beta
      with:
         node-version: '12'

    - name: Check Service Availability
      run: |
        sleep 60
        npm i puppeteer
        node ci/check_availability.js
        git config --local user.email "894597649@qq.com"
        git config --local user.name "lishuang"
        git status
        git add ci/screenshots/
        git commit -m "CI push sreenshots back"
        
    - name: Check poC message
      run: docker-compose logs poc

    - name: Check PoC Result
      run: bash check_poc.sh
   
    - name: Components Security Scan - container scan
      uses: anchore/scan-action@master
      with:
        image-reference: "lishuang-star/web:1.0"
        dockerfile-path: "./web"
        include-app-packages: true
        debug: true

    - name: Components Security Scan - anchore inline scan JSON results
      run: for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done
    - name: Components Security Scan - show vulnerabilities log in human readable format
      run: jq -r '.vulnerabilities[] | "\(.vuln)\t\(.severity)\t\(.package)\t\(.package_name)\t\(.package_version)"' ./anchore-reports/vulnerabilities.json | sort -k2 | grep -v Negligible

    - name: Push Screenshots And Traffic Back To Master
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
